trigger:
- master

pool:
  vmImage: "ubuntu-22.04"

steps:
      #- uses: actions/checkout@v2

      #- name: Install dependencies
       # run: npm ci
      #- name: Run developer tests
       # run: npm test

  -script: dotnet test
   displayName: Run unit tests
   
  -script: dotnet build --configuration $(buildconfiguration)
   displayName: Build appliction
   
   -script: docker build -t my-image:v1.0.
   displayName: Build image
   
   -script: docker push my-image:v1.0.
   displayName: push image
