trigger:
- master

pool:
  vmImage: "ubuntu-22.04"

steps:
- checkout: github.com/Suyeshk/aure-frontend-pipeline # Azure Repos Git repository in the same organization
  displayName: checkout repo
steps:
- script: npm install
  displayName: install npm 